### ISSUE TITLE
Log setting is not persisted?

### ISSUE THREAD

**Issue by rburgst** [rsyncOSX/rcloneosx#256]
When I click on the top right icon to configure the settings and set the log level to
"full logging".

The next time I open the settings screen, it is back to "no logging".

**Comment by rsyncOSX** [comment]
Hi, that is by default. The logs may be very large and appending new items to the log is done by first read the old logs, append new items and then write all logs to disk. I might have to refactor how logging is implemented to utilize your request...

**Comment by rburgst** [comment]
its ok to have it off by default. But when I manually set it to some other level and I open the settings screen again, I expect it to remember my decision.

**Comment by rsyncOSX** [comment]
I do agree.. Due to how logging is implemented now I have to refactor the logging part. RcloneOSX must handle 100K of log lines without affecting how RcloneOSX is running. I will look into it and it will be implemented in next version of RcloneOSX... Next version will be released in a couple of weeks.. OK?

**Comment by rsyncOSX** [comment]
A rc is uploaded, I have not tested how it is working with huge log files, but it should be working OK with that as well. Please report any issues...

https://github.com/rsyncOSX/rcloneosx/releases/tag/v1.6.1rc
